name: Build and Release
"on":
  push:
    tags:
    - v*

jobs:
  build:
    name: Build for Windows and Linux
    strategy:
      matrix:
        os:
        - linux
        - windows
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.21

    - name: Install Go dependencies
      run: go mod tidy

    - name: Cache Go modules
      uses: actions/cache@v3
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Extract version from Git tag
      id: vars
      run: echo "tag=${GITHUB_REF#refs/tags/v}" >> "$GITHUB_OUTPUT"

    - name: Build for ${{ matrix.os }}
      run: |
        VERSION=${{ steps.vars.outputs.tag }}
        if [[ "${{ matrix.os }}" == "linux" ]]; then
          GOOS=linux GOARCH=amd64 go build -ldflags "-X sv-cli/internal.Version=${VERSION}" -o sv
        elif [[ "${{ matrix.os }}" == "windows" ]]; then
          GOOS=windows GOARCH=amd64 go build -ldflags "-X sv-cli/internal.Version=${VERSION}" -o sv.exe
        fi
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: sv-${{ matrix.os }}
        path: sv*
  release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Download a build artifact
      uses: actions/download-artifact@v4
    - name: List downloaded artifacts
      run: ls -l
    - name: Create GitHub Release with Assets
      uses: softprops/action-gh-release@v2
      with:
        files: |-
          sv-linux/*
          sv-windows/*